import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";

const mitr = Mitr({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-global-mitr",
  display: "swap",
  style: ["normal"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mitr.variable}`}
      >
        {children} 
      </body>
    </html>
  );
}
